#!/usr/bin/env python
from gc import collect
import rospy
from inputs import get_gamepad
from std_msgs.msg import Int8

class DataCollection:

    def __init__(self):
        self.data_pub = rospy.Publisher('sp_input', Int8, queue_size=100)
        self.sensor_val = None
        self.r = rospy.Rate(1000)

    def collect_data(self):
        try:
            events = get_gamepad()
        except:
            rospy.logerr('*** No gamepad found. ***')
            return
        for event in events:
            if event.code == 'ABS_X':
                self.sensor_val = event.state

def main():
    rospy.init_node('data_collection')

    dc = DataCollection()
    
    while not rospy.is_shutdown():
        dc.collect_data()
        dc.data_pub.publish(dc.sensor_val)
        dc.r.sleep()

if __name__ == '__main__':
    main()